// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorTute.Models;

namespace RazorTute.Migrations
{
    [DbContext(typeof(TuteContext))]
    partial class TuteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("RazorTute.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<DateTime>("captureDate");

                    b.Property<decimal>("distance");

                    b.Property<string>("resources");

                    b.HasKey("ID");

                    b.ToTable("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
